export const Route = {
  Index: "/",
  Auth: {
    Signup: "/auth/signup",
    Login: "/auth/login",
    RoleSelection: "/auth/role-selection",
  },
  User: {
    PatientKyc: "/user/patient-kyc",
    DoctorKyc: "/user/doctor-kyc",
    HospitalKyc: "/user/hospital-kyc",
  },
  Dashboard: {
    Index: "/dashboard",
    PatientKyc: "/dashboard/patient-kyc",
    PatientKycDetail: "/dashboard/patient-kyc/:patientKycId",
    DoctorKyc: "/dashboard/doctor-kyc",
    DoctorKycDetail: "/dashboard/doctor-kyc/:doctorKycId",
    HospitalKyc: "/dashboard/hospital-kyc",
    HospitalKycDetail: "/dashboard/hospital-kyc/:hospitalKycId",
    MyKyc: "/dashboard/my-kyc",
    MyPatientKycResubmitForm: "/dashboard/my-kyc/patient-resubmit",
    HospitalSearchDoctor: "/dashboard/hospital/search-doctor",
    HospitalMyDoctors: "/dashboard/hospital/my-doctors",
    HospitalDoctorView: "/dashboard/hospital/my-doctors/:doctorKycId",
    PatientSearchHospitals: "/dashboard/patient/hospitals",
    PatientSearchHospitalDoctors: "/dashboard/patient/hospitals/:hospitalId",
    PatientSearchHospitalDoctorsView:
      "/dashboard/patient/hospitals/:hospitalId/:doctorId",
    PatientBookings: "/dashboard/patient/bookings",
    PatientMedicalHistory: "/dashboard/patient/medical-history",
    HospitalPatientBookings: "/dashboard/hospital/patient-bookings",
    DoctorGivenPrescriptions: "/dashboard/doctor/given-prescriptions",
  },
  NotFound: "*",
} as const;
